"""empty message

Revision ID: 197107b5e54e
Revises: 1b2c3756d718
Create Date: 2021-07-03 22:39:02.364087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197107b5e54e'
down_revision = '1b2c3756d718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.drop_column('Venue', 'looking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('looking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
